import type { Metadata } from "next";
import { Encode_Sans_Semi_Condensed, Geist_Mono } from "next/font/google";
import "./globals.css";

const encodeSansSemiCondensed = Encode_Sans_Semi_Condensed({
  variable: "--font-encode-sans-semi-condensed",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${encodeSansSemiCondensed.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
